[package]
name = "blu"
version = "0.2.1"
description = "LU factorization with dynamic Markowitz search and columnwise threshold pivoting"
edition = "2021"
license = "MIT"
repository = "https://github.com/rwl/blu"

[features]
debug = []
debug_extra = []